replicaCount: 1

image:
  repository: 783417120609.dkr.ecr.us-east-1.amazonaws.com/staging-payment-layer-card-api
  tag: ""
  pullPolicy: Always

env:
  ENV: staging
  DEBUG: False
  ENVIRONMENT: dev


serviceAccount:
  create: true
  name: payment-layer-card-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::783417120609:role/staging--layer-card-api@payment-layer-card-api

externalSecrets:
  enabled: true
  basePath: staging

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: payment-layer-card-api.staging.afya.systems
  hosts:
    - host: payment-layer-card-api.staging.afya.systems
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
