{{- if .Values.externalSecrets.enabled }}
{{- $basePath  := .Values.externalSecrets.basePath -}}
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: {{ include "payment-layer-card-api.fullname" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "payment-layer-card-api.fullname" . }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ include "payment-layer-card-api.fullname" . }}
{{- end }}
