ALTER TABLE "customers" ALTER COLUMN "document" TYPE VARCHAR(20);
ALTER TABLE "customers" ALTER COLUMN "phone" TYPE VARCHAR(20);
ALTER TABLE "customers" ALTER COLUMN "gender" TYPE VARCHAR(20);

ALTER TABLE "cards" ALTER COLUMN "brand" TYPE VARCHAR(20);
ALTER TABLE "cards" ALTER COLUMN "first_digits" TYPE VARCHAR(6);
ALTER TABLE "cards" ALTER COLUMN "last_digits" TYPE VARCHAR(4);
ALTER TABLE "cards" ALTER COLUMN "expire_year" TYPE VARCHAR(4);
ALTER TABLE "cards" ALTER COLUMN "expire_month" TYPE VARCHAR(2);

ALTER TABLE "card_tokens" ALTER COLUMN "gateway" TYPE VARCHAR(20);

ALTER TABLE "customer_tokens" ALTER COLUMN "gateway" TYPE VARCHAR(20);
